id: I48D3212F
ocr_import_info:
  timestamp: '2023-09-28T02:50:19.433594+00:00'
  batch_id: batch-dacd
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-28 03:43:26.658478+00:00
last_modified: 2023-09-28 03:43:26.658484+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM3155
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM3155
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དམ་པའི་ཆོས་མངོན་པའི་མཛོད་ཀྱི་རྣམ་པར་བཤད་པ་ཐར་ལམ་གསལ་བྱེད།
  languages:
  - bo
  author: དགེ་འདུན་གྲུབ་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9489510454674787
  ocr_word_median_confidence_index: 0.99321926
bases:
  I1NLM3155_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM3155_001
      total_pages: 454
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM3155_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.99321926
      ocr_word_mean_confidence_index: 0.9489510454674787
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
